### ISSUE TITLE
LinkerLine does not return its instance

### ISSUE THREAD

**Issue by Termit5606** [AhmedAyachi/LinkerLine#1]
```js
const aaaa = new LinkerLine({
        parent: canvas.value,
        start: startElement,
        end: endElement
    }).setOptions({
        color: '#A0AEC0',
        size: 1.5,
        endPlug: 'behind',
        startSocket: startSide,
        endSocket: endSide,
        path: 'fluid'
    })
```

aaaa - undefined

**Comment by Termit5606** [comment]
This is due to **setOptions**. If you use **setOptions** separately, everything is fine

```javascript
const line = new LinkerLine({
        parent: canvas.value,
        start: startElement,
        end: endElement
    })
    
    line.setOptions({
        color: '#A0AEC0',
        size: 1.5,
        endPlug: 'behind',
        startSocket: startSide,
        endSocket: endSide,
        path: 'fluid'
    })
```

**Comment by AhmedAyachi** [comment]
hello
#### case 1 :

    const line = new LinkerLine({
        parent: canvas.value,
        start: startElement,
        end: endElement
    })
    line.setOptions({...})

The line variable is the LinkerLine instance.
Everything is fine.

#### case 2 :

    const line = new LinkerLine({
            parent: canvas.value,
            start: startElement,
            end: endElement
    }).setOptions({...})
The line variable is storing the value returned by the ***setOptions*** method. 
setOptions returns nothing, that's why line here is ***undefined***.
Instead of calling setOptions like that, you just need to pass those options to the LinkerLine as Props as follows:

    const aaaa = new LinkerLine({
        parent: canvas.value,
        start: startElement,
        end: endElement,
        color: '#A0AEC0',
        size: 1.5,
        endPlug: 'behind',
        startSocket: startSide,
        endSocket: endSide,
        path: 'fluid'
    })
Happy coding.
