### ISSUE TITLE
Animation property error when boolean value specified

### ISSUE THREAD

**Issue by yhbk12** [AhmedAyachi/LinkerLine#3]
Hey man, great library here!

Was wondering if there was a way to make it such that, when someone vertically scrolls the page, the line moves properly and doesnt stay fixed on the page?

Would be very helpful! Let me know if you need more info

**Comment by yhbk12** [comment]
Also not a bug I don't think, but how do I replicate the basic animation I had with LeaderLine? I see you changed some field names, but passing `animation: true` no longer works. I assume its still enabled, could you let me know what to pass?

When I pass the animation params like I had been:
dash: { length: 10, gap: 3, animation: true },

I get the following:
TypeError: Cannot create property 'timing' on boolean 'true'

UPDATE:
Solved it, just needed to modify the object to this:

```
  dash: {
    easing: true,
    length: 10,
    gap: 3,
    animation: { animation: true, duration: 500 },
  },
```

**Comment by AhmedAyachi** [comment]
hello @yhbk12,
Thanks for reporting that, because it's indeed an implementation bug from my part, but I'm glad you found a workaround.
It will be fixed in a next version.
But just to mention, you only need the code to be just like:
```
dash:{
    length:10,
    gap:3,
    animation:{duration:500},
},
```
other fields are not required, ***easing*** should be in the animation object.

I'm happy to here that you liked this project, hope there are no other bugs.

About this: ***Was wondering if there was a way to make it such that, when someone vertically scrolls the page, the line moves properly and doesnt stay fixed on the page?***
I couldn't understand what you're pointing to, is there bug or a new feature you want me to implement ?
Can you please provide more info, thanks

**Comment by yhbk12** [comment]
@AhmedAyachi here's a video showing what I mean. Basically if the page vertically scrolls, the lines are fixed on the screen, they're not dynamic enough to move as the page moves. 

Is there any way to make the lines dynamically move when the page moves?

https://share.vidyard.com/watch/UKApB5nSZpN3oBxCGcKrbJ?

**Comment by yhbk12** [comment]
@AhmedAyachi any updates here? Thank you

**Comment by AhmedAyachi** [comment]
@yhbk12, couple questions, 
is the zoom what causing the lines to become improperly positioned ?
where are you inserting the lines, body or custom parent ?

**Comment by yhbk12** [comment]
@AhmedAyachi do you wanna do a quick video call and I can show you?

**Comment by yhbk12** [comment]
Will be much quicker, if youre free that'd be great!
https://meet.google.com/jqq-wxam-ezw

**Comment by AhmedAyachi** [comment]
not right now unfortunately, but I can meet you tomorrow if you're free

**Comment by yhbk12** [comment]
Yes lets do that. What time works best?

**Comment by yhbk12** [comment]
Fyi this is similar to the issue I have -- https://github.com/anseki/leader-line/issues/13#issue-329405560

**Comment by AhmedAyachi** [comment]
did you check the parent prop ?

**Comment by yhbk12** [comment]
That fixed it!! Thanks man you're a legend 🙏

**Comment by AhmedAyachi** [comment]
@yhbk12 , That's the whole point of this repo hhhh,
I'm happy I solved your problem, happy coding.
I'm gonna rename the issue to "animation boolean value error", cause that was really a bug

**Comment by yhbk12** [comment]
Great, sounds good. Thank you for the excellent package 🔥
